apiVersion:  argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-configmaps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ddor2812-dev/temp.git
    path: eso
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated: { prune: true, selfHeal: true }